name: Build and Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and verify with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Package artifacts
        run: mkdir staging && cp target/*.jar staging

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging
