name: Check

on:
  workflow_dispatch:
env:
 INP: true
 
jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run script
        run: chmod +x check.sh &&  VAL=$INP ./check.sh
  print:
    runs-on: ubuntu-latest
    needs: run_script
    steps:
      - name: Echo
        run: echo "::debug::This is a debug message"
