name: demo-app-cicd

on:
  workflow_dispatch: # Manually triggered event

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
          
        
      - name: Build with Maven
        run: mvn clean install
        
  test:
    needs: build
    runs-on: ubuntu-latest
     
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
       
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
          java-version: '17'
          distribution: 'temurin'
          
    - name: Run tests
      run: mvn test

  buildImage:
     needs: test
     runs-on: ubuntu-latest
     steps:
      - name: Build Docker image
        run: docker build -t my-springboot-app .

  publishImage:
     needs: test
     runs-on: ubuntu-latest
     steps:
      - name: Log in to Docker registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image to registry
        run: docker push my-springboot-app
