name: demo-app-cicd

on:
  workflow_dispatch: # Manually triggered event

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          cache-dependency-path: 'sub-project/pom.xml' # optional
          
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        
      - name: Build with Maven
        run: mvn clean install
        
      - name: Run tests
        run: mvn test
        
  # test:
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Run tests
  #       run: mvn test
